'use client';

import Heading from '@/components/Heading/Heading'
import React, { FC } from 'react'


const TermsScreen: FC<any> = ({ }) => {
    return (
        <div className='relative py-10 lg:py-12'>
            <div className='container'>
                <Heading desc={""} isCenter className="text-defaultBlue-100 mb-2">
                    Terms of Service
                </Heading>
                <div className="mt-3 py-3">
                    <ol className="list-decimal list-inside 2xl:mx-0 text-base">
                        <li className='mt-5'>ACCEPTANCE OF TERMS Welcome to Agoracom. Agoracom provides its service to you, subject to the following Terms of Service (“TOS”), which may be updated by us from time to time without notice to you. In addition, when using particular Agoracom services, you and Agoracom shall be subject to any posted guidelines or rules applicable to such services which may be posted from time to time. All such guidelines or rules are hereby incorporated by reference into the TOS. Agoracom also may offer other services from time to time, that are governed by different Terms of Services.</li>
                        <li className='mt-5'>DESCRIPTION OF SERVICE Agoracom currently provides users with access to a rich collection of on-line resources, including, various communications tools, online forums, and branded programming through its network of properties (the “Service”). Unless explicitly stated otherwise, any new features that augment or enhance the current Service, including the release of new Agoracom properties, shall be subject to the TOS. You understand and agree that the Service is provided “AS-IS” and that Agoracom assumes no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings. In order to use the Service, you must obtain access to the World Wide Web, either directly or through devices that access web-based content, and pay any service fees associated with such access. In addition, you must provide all equipment necessary to make such connection to the World Wide Web, including a computer and modem or other access device.</li>
                        <li className='mt-5'>YOUR REGISTRATION OBLIGATIONS In consideration of your use of the Service, you agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the Service’s registration form (such information being the “Registration Data”) and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or Agoracom has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Agoracom has the right to suspend or terminate your account and refuse any and all current or future use of the Service (or any portion thereof).</li>
                        <li className='mt-5'>Agoracom PRIVACY POLICY Registration Data and certain other information about you is subject to our Privacy Policy. For more information, please see our full privacy policy.</li>
                        <li className='mt-5'>MEMBER ACCOUNT, PASSWORD AND SECURITY You will receive a password and account designation upon completing the Service’s registration process. You are responsible for maintaining the confidentiality of the password and account, and are fully responsible for all activities that occur under your password or account. You agree to (a) immediately notify Agoracom of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session. Agoracom cannot and will not be liable for any loss or damage arising from your failure to comply with this Section 5.</li>
                        <li className='mt-5'>
                            MEMBER CONDUCT You understand that all information, data, text, software, music, sound, photographs, graphics, video, messages or other materials (“Content”), whether publicly posted or privately transmitted, are the sole responsibility of the person from which such Content originated. This means that you, and not Agoracom, are entirely responsible for all Content that you upload, post, email or otherwise transmit via the Service. Agoracom does not control the Content posted via the Service and, as such, does not guarantee the accuracy, integrity or quality of such Content. You understand that by using the Service, you may be exposed to Content that is offensive, indecent or objectionable. Under no circumstances will Agoracom be liable in any way for any Content, including, but not limited to, for any errors or omissions in any Content, or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed or otherwise transmitted via the Service. You agree to not use the Service to:
                            <ul className='list-disc list-inside'>
                                {/* <li className='mt-5'> */}
                                <p className='mt-5'>upload, post, email or otherwise transmit any Content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another’s privacy, hateful, or racially, ethnically or otherwise objectionable; b. harm minors in any way; c. impersonate any person or entity, including, but not limited to, a Agoracom official, forum leader, guide or host, or falsely state or otherwise misrepresent your affiliation with a person or entity; d. forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Service; e. upload, post, email or otherwise transmit any Content that you do not have a right to transmit under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements); f. upload, post, email or otherwise transmit any Content that infringes any patent, trademark, trade secret, copyright or other proprietary rights (“Rights”) of any party; g. upload, post, email or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” or any other form of solicitation, except in those areas (such as shopping rooms) that are designated for such purpose; h. upload, post, email or otherwise transmit any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; i. disrupt the normal flow of dialogue, cause a screen to “scroll” faster than other users of the Service are able to type, or otherwise act in a manner that negatively affects other users’ ability to engage in real time exchanges; j. interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service; k. intentionally or unintentionally violate any applicable U.S or Canadian local, state/provincial or international law, including, but not limited to, regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange, including, without limitation, the New York Stock Exchange, the American Stock Exchange, the Toronto Stock Exchange, the Canadian Venture Exchange, the Montreal Stock Exchange or the NASDAQ, and any regulations having the force of law; l. “stalk” or otherwise harass another; or m. collect or store personal data about other users.</p>
                                <p className='mt-5'>You acknowledge that Agoracom does not pre-screen Content, but that Agoracom community directors and Agoracom HUB Leaders shall have the right (but not the obligation) in their sole discretion to refuse, edit or remove any Content at any time. Without limiting the foregoing, Agoracom and its designees shall have the right to remove any Content that violates the TOS or is otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any Content, including any reliance on the accuracy, completeness, or usefulness of such Content. In this regard, you acknowledge that you may not rely on any Content created by Agoracom or submitted to Agoracom, including without limitation information in Agoracom Forums, Private Messages, Blogs, Videos, Newsflash and in all other parts of the Service. You acknowledge and agree that Agoracom may preserve Content and may also disclose Content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce the TOS; (c) respond to claims that any Content violates the rights of third-parties; or (d) protect the rights, property, or personal safety of Agoracom, its users and the public. You understand that the technical processing and transmission of the Service, including your Content, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</p>
                                {/* </li> */}
                            </ul>
                        </li>
                        <li className='mt-5'>SPECIAL ADMONITIONS FOR INTERNATIONAL USE Recognizing the global nature of the Internet, you agree to comply with all local rules regarding online conduct and acceptable Content. Specifically, you agree to comply with all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside.</li>
                        <li className='mt-5'>PUBLIC CONTENT POSTED TO Agoracom (a) For purposes of the TOS, “publicly accessible areas of the Service” are those accessible by the general public. By way of example, a publicly accessible area of the Service would include public Agoracom Message Boards, but would not include private Agora Member Forums. (b) With respect to Content you elect to post for inclusion in publicly accessible areas of Agoracom or that consists of photos or other graphics you elect to post to any other publicly accessible area of the Service, you grant Agoracom the world-wide, royalty free and non-exclusive license to reproduce, modify, adapt and publish such Content on the Service solely for the purpose of displaying, distributing and promoting the specific Agoracom to which such Content was submitted, or, in the case of photos or graphics, solely for the purpose for which such photo or graphic was submitted to the Service. This license exists only for as long as you elect to continue to include such Content on the Service and shall be terminated at the time you delete such Content from the Service. (c) With respect to all other Content you elect to post to other publicly accessible areas of the Service, you grant Agoracom the royalty-free, perpetual, irrevocable, non-exclusive and fully sublicensable right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such Content (in whole or part) worldwide and/or to incorporate it in other works in any form, media, or technology now known or later developed.</li>
                        <li className='mt-5'>INDEMNITY You agree to indemnify and hold Agoracom, and its subsidiaries, affiliates, officers, agents, co-branders or other partners, and employees, harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of Content you submit, post to or transmit through the Service, your use of the Service, your connection to the Service, your violation of the TOS, or your violation of any rights of another.</li>
                        <li className='mt-5'>NO RESALE OF SERVICE You agree not to reproduce, duplicate, copy, sell, resell or exploit for any commercial purposes, any portion of the Service, use of the Service, or access to the Service.</li>
                        <li className='mt-5'>GENERAL PRACTICES REGARDING USE AND STORAGE You acknowledge that Agoracom may establish general practices and limits concerning use of the Service, including without limitation the maximum number of days that message board postings or other uploaded Content will be retained by the Service, the maximum number of the maximum disk space that will be allotted on Agoracom’s servers on your behalf, and the maximum number of times (and the maximum duration for which) you may access the Service in a given period of time. You agree that Agoracom has no responsibility or liability for the deletion or failure to store any messages and other communications or other Content maintained or transmitted by the Service. You acknowledge that Agoracom reserves the right to log off accounts that are inactive for an extended period of time. You further acknowledge that Agoracom reserves the right to change these general practices and limits at any time, in its sole discretion, with or without notice.</li>
                        <li className='mt-5'>MODIFICATIONS TO SERVICE Agoracom reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that Agoracom shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</li>
                        <li className='mt-5'>TERMINATION You agree that Agoracom, in its sole discretion, may terminate your password, account (or any part thereof) or use of the Service, and remove and discard any Content within the Service, for any reason, including, without limitation, for lack of use or if Agoracom believes that you have violated or acted inconsistently with the letter or spirit of the TOS. Agoracom may also in its sole discretion and at any time discontinue providing the Service, or any part thereof, with or without notice. You agree that any termination of your access to the Service under any provision of this TOS may be effected without prior notice, and acknowledge and agree that Agoracom may immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such files or the Service. Further, you agree that Agoracom shall not be liable to you or any third-party for any termination of your access to the Service.</li>
                        <li className='mt-5'>DEALINGS WITH ADVERTISERS Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Service, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. You agree that Agoracom shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Service.</li>
                        <li className='mt-5'>LINKS The Service may provide, or third parties may provide, links to other World Wide Web sites or resources. Because Agoracom has no control over such sites and resources, you acknowledge and agree that Agoracom is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any Content, advertising, products, or other materials on or available from such sites or resources. You further acknowledge and agree that Agoracom shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such Content, goods or services available on or through any such site or resource.</li>
                        <li className='mt-5'>Agoracom’S PROPRIETARY RIGHTS You acknowledge and agree that the Service and any necessary software used in connection with the Service (“Software”) contain proprietary and confidential information that is protected by applicable intellectual property and other laws. You further acknowledge and agree that Content contained in sponsor advertisements or information presented to you through the Service or advertisers is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly authorized by Agoracom or advertisers, you agree not to modify, rent, lease, loan, sell, distribute or create derivative works based on the Service or the Software, in whole or in part. Agoracom grants you a personal, non-transferable and non-exclusive right and license to use the object code of its Software on a single computer; provided that you do not (and do not allow any third party to) copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, grant a security interest in or otherwise transfer any right in the Software. You agree not to modify the Software in any manner or form, or to use modified versions of the Software, including (without limitation) for the purpose of obtaining unauthorized access to the Service. You agree not to access the Service by any means other than through the interface that is provided by Agoracom for use in accessing the Service.</li>
                        <li className='mt-5'>
                            DISCLAIMER OF WARRANTIES YOU EXPRESSLY UNDERSTAND AND AGREE THAT:
                            <ul className='list-disc list-inside'>
                                {/* <li className='mt-5'> */}
                                <p className='mt-5'> YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. AGORACOM EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. b. Agoracom MAKES NO WARRANTY THAT (i) THE SERVICE WILL MEET YOUR REQUIREMENTS, (ii) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, AND (V) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED. c. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. d. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM Agoracom OR THROUGH OR FROM THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TOS.</p>
                                {/* </li> */}
                            </ul>
                        </li>
                        <li className='mt-5'>LIMITATION OF LIABILITY YOU EXPRESSLY UNDERSTAND AND AGREE THAT Agoracom SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF Agoracom HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICE; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (v) ANY OTHER MATTER RELATING TO THE SERVICE.</li>
                        <li className='mt-5'>EXCLUSIONS AND LIMITATIONS SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS OF SECTIONS 17 AND 18 MAY NOT APPLY TO YOU.</li>
                        <li className='mt-5'>SPECIAL ADMONITION FOR SERVICES RELATING TO FINANCIAL MATTERS If you intend to create or join any service, receive or request any news, messages, alerts or other information from the Service concerning companies, stock quotes, investments or securities, please read the above Sections 17 and 18 again. They go doubly for you. In addition, for this type of information particularly, the phrase “Let the investor beware” is apt. The Service is provided for informational purposes only, and no Content included in the Service is intended for trading or investing purposes. Agoracom shall not be responsible or liable for the accuracy, usefulness or availability of any information transmitted via the Service, and shall not be responsible or liable for any trading or investment decisions made based on such information.</li>
                        <li className='mt-5'>NOTICE Notices to you may be made via either email, private message, message board posting or regular mail. It is your sole responsibility to maintain a current e-mail address to receive any such notifications. The Service may also provide notices of changes to the TOS or other matters by displaying notices or links to notices to you generally on the Service.</li>
                        <li className='mt-5'>TRADEMARK INFORMATION Agoracom, the Agoracom logo, Agoracom trademarks and service marks, and other Agoracom related logos and product and service names are trademarks of Agora Trademarks. (the “Agoracom Marks”). Without Agora Trademarks prior permission, you agree not to display or use in any manner, the Agoracom Marks.</li>
                        <li className='mt-5'>
                            COPYRIGHTS and COPYRIGHT AGENTS Agoracom respects the intellectual property of others, and we ask our users to do the same. If you believe that your work has been copied in a way that constitutes copyright infringement, please provide Agoracom’s Copyright Agent the following information:
                            <ul className='list-disc list-inside'>
                                {/* <li className='mt-5'> */}
                                <p className='mt-5'>
                                    an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; 2. a description of the copyrighted work that you claim has been infringed; 3. a description of where the material that you claim is infringing is located on the site; 4. your address, telephone number, and email address; 5. a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; 6. a statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf. Agoracom’s Copyright Agent for Notice of claims of copyright infringement on its site is Jeff Cohen who can be reached through our contact page http://agoracom.com/about-and-contact
                                </p>
                                {/* </li> */}
                            </ul>
                        </li>
                        <li className='mt-5'>
                            GENERAL INFORMATION The TOS constitute the entire agreement between you and Agoracom and govern your use of the Service, superceding any prior agreements between you and Agoracom. You also may be subject to additional terms and conditions that may apply when you use affiliate services, third-party content or third-party software. The TOS and the relationship between you and Agoracom shall be governed by the laws of the Province of Ontario without regard to its conflict of law provisions. You and Agoracom agree to submit to the personal and exclusive jurisdiction of the courts located within the Province of Ontario, Canada. The failure of Agoracom to exercise or enforce any right or provision of the TOS shall not constitute a waiver of such right or provision. If any provision of the TOS is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of the TOS remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or the TOS must be filed within one (1) year after such claim or cause of action arose or be forever barred. The section titles in the TOS are for convenience only and have no legal or contractual effect.
                            <ul className='list-disc list-inside'>
                                {/* <li className='mt-5'> */}
                                <p className='mt-5'>
                                    AGORACOM is a financial news and information site, not an investment advisor.  Making investment decisions based on information published on AGORACOM, or any internet site for that matter, is more than unwise, it is folly. AGORACOM also provides online marketing and/or online investor relations services to public companies. We maintain an updated list of clients at http://agoracom.com/clients. AGORACOM does not provide investing or trading recommendations related to our clients because we are not an investment advisor. In fact, except for shares received as compensation from any such clients, we do not buy or sell client shares in the open market. Given the fact we are compensated by such companies, want to stay in business and often receive shares as compensation for our services from such companies, assume we are horribly conflicted when presenting client materials and never, ever make an investment in any such client until you’ve spoken with an investment advisor (which we are not), your spouse and your parents. By using our private messaging systems, users are taking any and all risks associated with chatting into their own hands; the internet is full of crazies and we do not monitor the private messaging system … because its private. If you believe a violation has taken place using the private messaging system, or you have been threatened in any way, please report it through our contact page http://agoracom.com/about-and-contact, as well as, any authorities if you believe you are in imminent danger. We reserve the right to modify the terms of this disclosure without notice.
                                </p>
                                {/* </li> */}
                            </ul>
                        </li>
                        <li className='mt-5'>VIOLATIONS If you are logged in, please report violations by using the “Report Violation” button at the end of all posts. If you are not logged in, please report all violations through our contact page http://agoracom.com/about-and-contact</li>
                    </ol>
                </div>
            </div>

        </div>

    )
}

export default TermsScreen;